spring:
  h2.console:
      enabled: true
      path: /console
  datasource:
      initialize: true
      url: jdbc:h2:mem:testdb
      driver-class-name: org.h2.Driver
      type: com.zaxxer.hikari.HikariDataSource
      hikari:
        maximum-pool-size: 10
        data-source-properties:
          implicitCachingEnabled: true
          fastConnectionFailoverEnabled: true
  jpa:
      hibernate:
        ddl-auto: update
      properties:
        hibernate:
          dialect: org.hibernate.dialect.H2Dialect
          show-sql: true
          format-sql: false
          use-sql-comments: false
  batch:
    job:
      enabled: false
